### PR TITLE
Configurable hash functions

### PR DESCRIPTION
**Pull request by willHol**
This was a use case I encountered in a personal project. I'm not sure if this is the best implementation, however it works well.

### CODE REVIEW

**Comment by mwmiller** [comment]
I'd be a lot more on-board if you included some documentation of the fact that this configuration option exists... and explained a use-case.

On the surface, it's a slightly slower no-op, otherwise. 😁  I'm not sure how useful this will be given the way configs are released.

**Comment by willHol** [comment]
Sorry for that. I just wanted to get your thoughts.

So my particular use case is I'm building a client for interfacing with a cryptocurrency node (RaiBlocks). These blocks are being signed via ed25519, however the cryptocurrency uses Blake2 as the hash function for ed25519. I'm including this project as a dependency for my own, however hex doesn't allow git dependencies - so I can't list my fork as a dependency. Hence my choices are either hard forking and publishing that to hex, which feels a little wrong, or trying to get some solution implemented for this repository.

Admittedly I should probably implement it in a different way, perhaps using macros so that the function clause is expanded at compile time - to eliminate the overhead - and I would be happy to document this.

**Comment by willHol** [comment]
I've reimplemented it as a macro. Which should eliminate the performance impact, added documentation and squashed it into a single commit. Let me know what you think :)

**Comment by mwmiller** [comment]
I like!  I'll publish a new `1.1.0` version on hex shortly for everyone to use.

Thanks for the contribution!

**Comment by willHol** [comment]
Thank you!

**Comment by mwmiller** [comment]
No problem!  I looked over your project a little bit.  You might also be interested in my `BaseX` module:  https://hex.pm/packages/basex

```

**Comment by mwmiller** [comment]
No problem!  I looked over your project a bit, not having any familiarity with RaiBlocks.  There's a chance you might also be interested in my `BaseX` module: https://hex.pm/packages/basex

```
 iex(1)> BaseX.prepare_module("Base32", "13456789abcdefghijkmnopqrstuwxyz", 5)
BaseX.Base32          
iex(2)> BaseX.Base32.encode(<<8, 147, 56, 91, 237>>)
"34bmipzf"
iex(3)> BaseX.Base32.decode("34bmipzf")
<<8, 147, 56, 91, 237>>
iex(4)> 
```

It might not fully meet your needs, but thought it worth mentioning.

Best of luck!

**Pull request merged**
