### PR TITLE
Fix: Elixir 1.11 warnings

### PR DESCRIPTION
**Pull request by mad42**
Fix Elixir 11.1 warnings:
```shell
==> ed25519
Compiling 2 files (.ex)
warning: :crypto.hash/2 defined in application :crypto is used by the current application but the current application does not directly depend on :crypto. To fix this, you must do one of:

  1. If :crypto is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :crypto is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :crypto, you may optionally skip this warning by adding [xref: [exclude: :crypto]] to your "def project" in mix.exs

  lib/ed25519.ex:67: Ed25519.hash/1

warning: :crypto.mod_pow/3 defined in application :crypto is used by the current application but the current application does not directly depend on :crypto. To fix this, you must do one of:

  1. If :crypto is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :crypto is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :crypto, you may optionally skip this warning by adding [xref: [exclude: :crypto]] to your "def project" in mix.exs

Found at 2 locations:
  lib/ed25519.ex:75: Ed25519.expmod/3
  lib/ed25519.ex:79: Ed25519.expmod/3

warning: :crypto.strong_rand_bytes/1 defined in application :crypto is used by the current application but the current application does not directly depend on :crypto. To fix this, you must do one of:

  1. If :crypto is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :crypto is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :crypto, you may optionally skip this warning by adding [xref: [exclude: :crypto]] to your "def project" in mix.exs

  lib/ed25519.ex:179: Ed25519.generate_key_pair/0
```

### CODE REVIEW

**Comment by mad42** [comment]
closes #6

**Comment by mad42** [comment]
Hello @mwmiller !
Can you review #5 please ?
Thanks you :)

**Comment by mwmiller** [comment]
Sorry this took so long.  I've been moving between laptops and this somehow got lost in the translation.  I'll release a new version to hex in a few.

**Comment by mad42** [comment]
Many thanks, waiting for the release ;)

**Comment by mad42** [comment]
@mwmiller take a look at (https://github.com/mwmiller/curve25519_ex/pull/3) before releasing https://github.com/mwmiller/kcl

**Comment by mwmiller** [comment]
I see I have gotten my curve and ed repos confused.  I appreciate you taking the time to keep me in line.

**Pull request merged**
